- name: setup {{ component }} service
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: daeman reload
  ansible.builtin.systemd.service:
    daemon_reload: yes  