- name: catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service 

- name: deman reload
  ansible.builtin.systemd.service:
    daemon_reload: yes  